module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    'tailwindcss/nesting': 'postcss-nesting',
    'postcss-mobile-hover': {},
    'postcss-pxtorem': {
      propList: [
        'font',
        'font-size',
        'line-height',
        'letter-spacing',
        'margin',
        'margin-top',
        'margin-bottom',
        'margin-left',
        'margin-right',
        'padding',
        'padding-top',
        'padding-bottom',
        'padding-left',
        'padding-right',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'transform',
      ],
      // mediaQuery: true,
    },
  },
};
