import Head from 'next/head';
import Image from '../components/Image';
import {
  useDeferredValue,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  useTransition,
} from 'react';
import Space from '../img/space.jpg';
import { useAtom } from 'jotai';
import { scrollAtom } from '../atoms/scroll';

export default function Home() {
  const [scroll] = useAtom(scrollAtom);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-[1200px]">
        <div className="h-[500px] w-full bg-red-600"></div>
        <div
          style={{
            transform: `translateY(-${Math.min(200, scroll / 5)}px)`,
          }}
          className="p-4 pt-2 text-center text-4xl font-bold underline"
        >
          Hello
        </div>
      </div>
    </div>
  );
}
